In [2]:
import xarray as xr

In [16]:
data = xr.open_dataset('../data/temperature/MERRA2_300.tavgM_2d_flx_Nx.200501.nc4')
data

<xarray.Dataset> Size: 77MB
Dimensions:          (lon: 576, lat: 361, time: 1)
Coordinates:
  * lon              (lon) float64 5kB -180.0 -179.4 -178.8 ... 178.8 179.4
  * lat              (lat) float64 3kB -90.0 -89.5 -89.0 ... 89.0 89.5 90.0
  * time             (time) datetime64[ns] 8B 2005-01-01T00:30:00
Data variables: (12/92)
    BSTAR            (time, lat, lon) float32 832kB ...
    CDH              (time, lat, lon) float32 832kB ...
    CDM              (time, lat, lon) float32 832kB ...
    CDQ              (time, lat, lon) float32 832kB ...
    CN               (time, lat, lon) float32 832kB ...
    DISPH            (time, lat, lon) float32 832kB ...
    ...               ...
    Var_TSTAR        (time, lat, lon) float32 832kB ...
    Var_ULML         (time, lat, lon) float32 832kB ...
    Var_USTAR        (time, lat, lon) float32 832kB ...
    Var_VLML         (time, lat, lon) float32 832kB ...
    Var_Z0H          (time, lat, lon) float32 832kB ...
    Var_Z0M          (time, lat, lon) float32 832kB ...
Attributes: (12/30)
    History:                           Original file generated: Sat Jun 27 19...
    Filename:                          MERRA2_300.tavgM_2d_flx_Nx.200501.nc4
    Comment:                           GMAO filename: d5124_m2_jan00.tavg1_2d...
    Conventions:                       CF-1
    Institution:                       NASA Global Modeling and Assimilation ...
    References:                        http://gmao.gsfc.nasa.gov
    ...                                ...
    DataResolution:                    0.5 x 0.625
    Source:                            CVS tag: GEOSadas-5_12_4
    Contact:                           http://gmao.gsfc.nasa.gov
    identifier_product_doi:            10.5067/0JRLVL8YV2Y4
    RangeBeginningTime:                00:00:00.000000
    RangeEndingTime:                   23:59:59.000000

In [21]:
import numpy as np
print(data['TLML'][0].attrs)
print(data['TLML'][0].values)

{'long_name': 'surface_air_temperature', 'units': 'K', 'fmissing_value': 1000000000000000.0, 'vmax': 1000000000000000.0, 'vmin': -1000000000000000.0, 'valid_range': array([-1.e+15,  1.e+15], dtype=float32)}
[[245.7565  245.7565  245.7565  ... 245.7565  245.7565  245.7565 ]
 [245.12558 245.12805 245.13086 ... 245.11803 245.12047 245.12306]
 [244.56572 244.57332 244.5806  ... 244.54393 244.55106 244.55853]
 ...
 [250.08517 250.07405 250.06297 ... 250.1189  250.10771 250.09631]
 [250.24438 250.23943 250.23425 ... 250.26024 250.25496 250.2497 ]
 [250.32109 250.32109 250.32109 ... 250.32109 250.32109 250.32109]]


In [22]:
# 1 DU = 21.415 µg(O3)/m3